feat(HII-5211): creating a migrate action to separate migrations from nodejs startup script
extenda/shared-workflows pull request #32
Opened 2022-10-28 10:38 UTC by koppathachan

2022-10-28 10:48 UTC, glebbash requested changes

2022-10-28 10:48 UTC, glebbash commented on composite-actions/nodejs-generic-api/migrate/action.yaml
> +          DB_PASS: postgres_user_profile_role_password
This secrets are for UPS db only

2022-10-28 10:48 UTC, artemka-debug requested changes

2022-10-28 10:48 UTC, artemka-debug commented on composite-actions/nodejs-generic-api/migrate/action.yaml
> +        secrets: |
What will happen, if those secrets are not defined in GCP?

2022-10-28 10:48 UTC, artemka-debug commented on composite-actions/nodejs-generic-api/migrate/action.yaml
> +        secrets: |
Like in other projects, we have defferent names for secrets

2022-10-28 14:58 UTC, glebbash approved these changes

2022-10-28 15:11 UTC, glebbash requested changes
Please name this action `prisma-migrate` or something more specific then just `migrate`

2022-10-31 07:13 UTC, koppathachan commented
> Please name this action `prisma-migrate` or something more specific then just `migrate`

I will rename it to db-migrate since it need not be specific to prisma? @glebbash

2022-11-01 13:28 UTC, glebbash commented
Maybe not prisma but CloudSQL instead, the set of envs is very specific and won't work for Spanner for example

2022-11-02 07:15 UTC, mdovhopo approved these changes

2022-11-02 07:33 UTC, merged